version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8001:8001"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    env_file:
      - .env
    depends_on:
      - db

